/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-10-06 21:50:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class preguntasSite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <title>Quien Quiere Ser Millonario</title>\n");
      out.write("    <nav class=\"navbar navbar-light\" style=\"background-color: #005cbf\">\n");
      out.write("        <div style=\"font-size: 80px; color: #f7f7f7\" class=\"navbar-brand\">\n");
      out.write("            <img src=\"image/logo-qqsm.png\" width=\"220\" height=\"140\" class=\"d-inline-block align-top\" alt=\"\"/>\n");
      out.write("            Quién Quiere Ser Millonario!\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #bee5eb\">\n");
      out.write("\n");
      out.write("    <nav aria-label=\"...\">\n");
      out.write("        <ul class=\"pagination pagination-lg\">\n");
      out.write("            <li class=\"page-item active\" aria-current=\"page\">\n");
      out.write("                <span class=\"page-link\">\n");
      out.write("                    Preguntas\n");
      out.write("                    <span class=\"sr-only\">(current)</span>\n");
      out.write("                </span>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"page-item\"><a class=\"page-link\" href=\"index.jsp\">Inicio</a></li>\n");
      out.write("        </ul>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div style=\"margin-top: 50px; margin-left: 100px\" class =\"page-header\">\n");
      out.write("        <h1>Registro de Preguntas</h1>\n");
      out.write("    </div>\n");
      out.write("    <div>\n");
      out.write("        <form id=\"preguntaForm\" name=\"preguntaForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/PreguntaCtr\" method=\"post\" style=\"margin: 100px; margin-top: 30px\" class=\"was-validated\">\n");
      out.write("            <input type=\"hidden\" id=\"optionHidenn\" name=\"optionHidenn\" value=\"4\">\n");
      out.write("            <input type=\"hidden\" id=\"idPreguntaHidden\" name=\"idPreguntaHidden\" value=\"0\">\n");
      out.write("            <div class=\"form-row\">\n");
      out.write("                <div>\n");
      out.write("                    <input style=\"margin-right: 900px\" type=\"text\" class=\"form-control is-invalid\" id=\"enunciadoCtx\" name=\"enunciadoCtx\" placeholder=\"Enunciado\" required>\n");
      out.write("                    <input style=\"margin-right: 900px; margin-top: 10px\" type=\"text\" class=\"form-control is-invalid\" id=\"valorCtx\" name=\"valorCtx\" placeholder=\"Valor\" required>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <button style=\"margin-top: 20px; margin-left: 20px\" type=\"button\" id=\"registrarBtn\" name=\"registrarBtn\" class=\"btn btn-success\" onclick=\"generalAjax(0,1)\">Registrar</button>\n");
      out.write("                    <button style=\"margin-top: 20px; margin-left: 20px\" type=\"button\" id=\"modificarBtn\" name=\"modificarBtn\" class=\"btn btn-warning\" style=\"display: none\">Modificar</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    <div  style=\"margin: 100px\">\n");
      out.write("        <table id=\"preguntasTbl\" name=\"preguntasTbl\" class=\"table table-striped\">\n");
      out.write("\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"js/jquery-3.4.1.min.js\"></script>            \n");
      out.write("    <script src=\"js/UtilesJquery.js\"></script>\n");
      out.write("    <script src=\"js/scripts.js\" type=\"text/javascript\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
